# Generated by Django 5.2.15 on 2026-10-05 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryservicesinfo',
            name='name_catrgory_work',
        ),
        migrations.AddField(
            model_name='categoryservicesinfo',
            name='name_category_work',
            field=models.CharField(default='ОСНОВНАЯ', max_length=120, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicesinfo',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.categoryservicesinfo'),
        ),
    ]
