# Generated by Django 5.2.15 on 2026-07-06 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_service', models.CharField(max_length=100, verbose_name='Название сервиса')),
                ('address', models.CharField(max_length=150, verbose_name='Адрес сервиса')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
