# Generated by Django 5.2.15 on 2026-07-08 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceinfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='serviceinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='service_info', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
