# Generated by Django 5.2.15 on 2026-07-14 09:34

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0005_documentinformation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentinformation',
            name='main_text',
        ),
        migrations.AddField(
            model_name='documentinformation',
            name='content',
            field=tinymce.models.HTMLField(default='Тут будет текст для документов'),
        ),
    ]
