# Generated by Django 5.2.15 on 2026-07-15 12:50

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0006_remove_documentinformation_main_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentinformation',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
