# Generated by Django 5.2.15 on 2026-07-26 10:31

import django.db.models.deletion
import profile_user.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0007_alter_documentinformation_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormsForOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_order', models.CharField(max_length=100, null=True)),
                ('json_forms', models.JSONField(default=profile_user.models.get_dict_for_json_forms)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms_for_order', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
