# Generated by Django 5.2.15 on 2026-08-25 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0008_formsfororder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workersinfo',
            name='patronymic',
        ),
    ]
