# Generated by Django 5.2.15 on 2026-08-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0009_remove_workersinfo_patronymic'),
    ]

    operations = [
        migrations.AddField(
            model_name='workersinfo',
            name='phone',
            field=models.CharField(max_length=16, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='workersinfo',
            name='role',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
