# Generated by Django 5.2.15 on 2026-08-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0010_workersinfo_phone_workersinfo_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workersinfo',
            name='phone',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
