# Generated by Django 5.2.15 on 2026-08-29 16:30

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0011_alter_workersinfo_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentinformation',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
