from .adoption import ShowAdoptionView
from .cancel import ShowCancellView
from .categories_info import ShowCategoriesView
from .complete import ShowCompleteView
from .garanty import ShowGarantyView
from .profile import UserProfileView
from .service_info import ServiceInfoView
from .tinymce import ShowDocumentView
from .workers import WorkersAddView
from .forms_for_orders import FormsForOrdersEdit
from .get_individual_field_modal import EditIndividualCenterForm
from .create_new_form import CreateNewFormInCategory
from .delete_custom_form import DeleteCustomForm
from .backup_default_doc import BackupDocumentView
from .main_storage import StorageCustomView
from .acceptable_storage import StorageAcceptableCustomView
from .removal_storage import StorageRemovalCustomView