from .adoption import ShowAdoptionView
from .cancel import ShowCancellView
from .categories_info import ShowCategoriesView
from .complete import ShowCompleteView
from .garanty import ShowGarantyView
from .profile import UserProfileView
from .service_info import ServiceInfoView
from .tinymce import ShowDocumentView
from .workers_info import WorkersAddView