# Generated by Django 5.2.15 on 2026-10-08 07:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile_user', '0012_alter_documentinformation_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_for_order', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'phone')},
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(db_index=True, max_length=60)),
                ('type_of_order', models.CharField(max_length=20)),
                ('device_type', models.CharField(db_index=True, max_length=40)),
                ('color_of_device', models.CharField(db_index=True, max_length=40)),
                ('name_of_device', models.CharField(db_index=True, max_length=150)),
                ('problem_with_device', models.CharField(db_index=True, max_length=150)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('dealdine', models.DateTimeField(blank=True, null=True)),
                ('form_with_order_information', models.JSONField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_order', to='orders.client')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profile_user.workersinfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
