# Generated by Django 5.2.15 on 2026-10-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='important',
            field=models.BooleanField(default=False),
        ),
    ]
