# Generated by Django 5.2.15 on 2026-09-02 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('individual_code', models.IntegerField(max_length=100)),
                ('name_product', models.CharField(max_length=120)),
                ('quantity_at_the_purchase', models.IntegerField(max_length=100)),
                ('supplier', models.CharField(blank=True, max_length=120)),
                ('buy_price', models.IntegerField(max_length=100)),
                ('retail_price', models.IntegerField(max_length=100)),
                ('minimum_items_for_notification', models.IntegerField(default=10, max_length=100)),
                ('remainder', models.IntegerField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
