# Generated by Django 5.2.15 on 2026-09-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storageinfo',
            name='buy_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='storageinfo',
            name='individual_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='storageinfo',
            name='minimum_items_for_notification',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='storageinfo',
            name='quantity_at_the_purchase',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='storageinfo',
            name='remainder',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='storageinfo',
            name='retail_price',
            field=models.IntegerField(),
        ),
    ]
