# Generated by Django 5.2.15 on 2026-09-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_alter_storageinfo_buy_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storageinfo',
            name='minimum_items_for_notification',
            field=models.IntegerField(default=5),
        ),
    ]
