# Generated by Django 5.2.15 on 2026-09-04 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_alter_storageinfo_minimum_items_for_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storageinfo',
            name='individual_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
