# Generated by Django 5.2.15 on 2026-09-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_alter_storageinfo_individual_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storageinfo',
            name='remainder',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
