# Generated by Django 5.2.15 on 2026-09-04 11:13

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_alter_storageinfo_remainder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='storageinfo',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 9, 4, 11, 13, 27, 576042, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='HistoryStorageInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_operation', models.CharField(max_length=100)),
                ('individual_code_history', models.IntegerField()),
                ('name_product_history', models.CharField(max_length=120)),
                ('quantity_at_the_purchase_history', models.IntegerField()),
                ('buy_price', models.IntegerField()),
                ('retail_price', models.IntegerField()),
                ('supplier_history', models.CharField(max_length=120)),
                ('remainder_history', models.IntegerField(blank=True, null=True)),
                ('time_of_operation_history', models.DateTimeField()),
                ('created_at_history', models.DateTimeField(default=datetime.datetime(2026, 9, 4, 11, 13, 27, 576921, tzinfo=datetime.timezone.utc))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_storage', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
