# Generated by Django 5.2.15 on 2026-09-04 11:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_storageinfo_created_at_historystorageinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historystorageinfo',
            name='created_at_history',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historystorageinfo',
            name='time_of_operation_history',
            field=models.DateTimeField(default=datetime.datetime(2026, 9, 4, 11, 26, 55, 95322, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='storageinfo',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 9, 4, 11, 26, 55, 94284, tzinfo=datetime.timezone.utc)),
        ),
    ]
