# Generated by Django 5.2.15 on 2026-09-06 10:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_alter_historystorageinfo_created_at_history_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historystorageinfo',
            old_name='buy_price',
            new_name='buy_price_history',
        ),
        migrations.RenameField(
            model_name='historystorageinfo',
            old_name='retail_price',
            new_name='retail_price_history',
        ),
        migrations.AlterField(
            model_name='historystorageinfo',
            name='time_of_operation_history',
            field=models.DateTimeField(default=datetime.datetime(2026, 9, 6, 10, 48, 39, 317498, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='storageinfo',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 9, 6, 10, 48, 39, 316076, tzinfo=datetime.timezone.utc)),
        ),
    ]
