# Generated by Django 5.2.15 on 2026-09-06 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0008_rename_buy_price_historystorageinfo_buy_price_history_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historystorageinfo',
            name='time_of_operation_history',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='storageinfo',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 9, 6, 11, 1, 16, 516308, tzinfo=datetime.timezone.utc)),
        ),
    ]
