# Generated by Django 5.2.15 on 2026-09-06 12:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0009_alter_historystorageinfo_time_of_operation_history_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historystorageinfo',
            name='created_at_history',
        ),
        migrations.RemoveField(
            model_name='historystorageinfo',
            name='individual_code_history',
        ),
        migrations.RemoveField(
            model_name='historystorageinfo',
            name='quantity_at_the_purchase_history',
        ),
        migrations.RemoveField(
            model_name='historystorageinfo',
            name='retail_price_history',
        ),
        migrations.RemoveField(
            model_name='historystorageinfo',
            name='type_of_operation',
        ),
        migrations.AddField(
            model_name='historystorageinfo',
            name='quantity_history',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historystorageinfo',
            name='time_created_history',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historystorageinfo',
            name='type_of_operation_history',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='historystorageinfo',
            name='buy_price_history',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historystorageinfo',
            name='name_product_history',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='historystorageinfo',
            name='supplier_history',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='historystorageinfo',
            name='time_of_operation_history',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storageinfo',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 9, 6, 12, 17, 6, 426801, tzinfo=datetime.timezone.utc)),
        ),
    ]
