# Generated by Django 5.2.15 on 2026-09-06 12:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0010_remove_historystorageinfo_created_at_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historystorageinfo',
            name='individual_code_history',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storageinfo',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 9, 6, 12, 25, 52, 700825, tzinfo=datetime.timezone.utc)),
        ),
    ]
