# Generated by Django 5.2.15 on 2026-09-08 08:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0011_historystorageinfo_individual_code_history_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storageinfo',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 9, 8, 8, 29, 56, 592985, tzinfo=datetime.timezone.utc)),
        ),
    ]
