# Generated by Django 5.2.15 on 2026-09-11 11:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0012_alter_storageinfo_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historystorageinfo',
            name='name_product_history',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='storageinfo',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 9, 11, 11, 38, 10, 685718, tzinfo=datetime.timezone.utc)),
        ),
    ]
