# Generated by Django 5.2.15 on 2026-09-14 11:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0013_alter_historystorageinfo_name_product_history_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historystorageinfo',
            name='quantity_history',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='storageinfo',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 9, 14, 11, 0, 22, 723650, tzinfo=datetime.timezone.utc)),
        ),
    ]
