# Generated by Django 5.2.15 on 2026-09-16 07:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0014_alter_historystorageinfo_quantity_history_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storageinfo',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 9, 16, 7, 14, 33, 175051, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='storageinfo',
            name='supplier',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
