# Generated by Django 5.2.15 on 2026-09-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0016_alter_storageinfo_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historystorageinfo',
            name='buy_price_history',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='storageinfo',
            name='buy_price',
            field=models.DecimalField(decimal_places=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='storageinfo',
            name='retail_price',
            field=models.DecimalField(decimal_places=0, max_digits=11),
        ),
    ]
