# Generated by Django 5.2.15 on 2026-09-28 09:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0017_alter_historystorageinfo_buy_price_history_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historystorageinfo',
            name='time_created_history',
        ),
        migrations.AlterField(
            model_name='historystorageinfo',
            name='time_of_operation_history',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
