from .main_storage import StorageCustomView
from .acceptable_storage import StorageAcceptableCustomView
from .removal_storage import StorageRemovalCustomView
from .history_storage import StorageHistoryCustomView