from .main_storage import StorageCustomView
from .acceptable_storage import StorageAcceptableCustomView
from .removal_storage import StorageRemovalCustomView
from .garanty_storage import StorageGarantyCustomView
from .form_removal import FormRemovalCustomView
from .select_django_autocomplete import CountryAutocomplete
from .history_and_filter_storage import FilterHistoryCustomView