# Generated by Django 5.2.15 on 2026-09-24 19:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_registration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashAccount',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='cash_account', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('money_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=11)),
            ],
        ),
        migrations.CreateModel(
            name='FinanceHistoryInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_operation', models.CharField(choices=[('in', 'Поступление'), ('out', 'Исход')], max_length=3)),
                ('category_of_operation', models.CharField(blank=True, max_length=100, null=True)),
                ('number_in_the_operation', models.DecimalField(decimal_places=2, max_digits=11)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
