# Generated by Django 5.2.15 on 2026-09-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financehistoryinfo',
            name='category_of_operation',
            field=models.CharField(choices=[('Продажа', 'Продажа'), ('Покупка', 'Покупка'), ('Гарантийный возврат', 'Гарантийный возврат'), ('Прочее', 'Прочее')], max_length=22),
        ),
        migrations.AlterField(
            model_name='financehistoryinfo',
            name='type_of_operation',
            field=models.CharField(choices=[('Поступление', 'Поступление'), ('Исход', 'Исход')], max_length=15),
        ),
    ]
