# Generated by Django 5.2.15 on 2026-09-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_financehistoryinfo_category_of_operation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financehistoryinfo',
            name='number_in_the_operation',
            field=models.DecimalField(decimal_places=0, max_digits=11),
        ),
    ]
