# Generated by Django 5.2.15 on 2026-09-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_financehistoryinfo_number_in_the_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='financehistoryinfo',
            name='product_code',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financehistoryinfo',
            name='product_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
