# Generated by Django 5.2.15 on 2026-09-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_financehistoryinfo_product_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financehistoryinfo',
            name='supplier',
            field=models.CharField(default=0, max_length=120),
            preserve_default=False,
        ),
    ]
