# Generated by Django 5.2.15 on 2026-10-01 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_financehistoryinfo_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financehistoryinfo',
            name='product_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financehistoryinfo',
            name='product_name',
            field=models.CharField(default='Нет данных', max_length=120),
        ),
        migrations.AlterField(
            model_name='financehistoryinfo',
            name='supplier',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
