# Generated by Django 5.2.15 on 2026-10-02 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_financehistoryinfo_product_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financehistoryinfo',
            name='product_name',
            field=models.CharField(default='', max_length=120),
        ),
    ]
